[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "propms"
version = "1.7.0"
description = "Property Management Solution"
authors = [
    { name = "Aakvatech", email = "info@aakvatech.com" },
]
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.10"
dependencies = []

[project.urls]
Homepage = "https://aakvatech.com"
Repository = "https://github.com/aakvatech/PropMS"

[tool.flit.module]
name = "propms"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
erpnext = ">=15.0.0,<16.0.0"